### ISSUE TITLE
Move css inside a html to external file

### ISSUE THREAD

**Issue by shinneider** [shinneider/django-admin-search#22]
In the file `django_admin_search/templates/admin/custom_search_form.html` has many lines of css.

i need to move this lines of css, to a external css file, loaded in the html

**Comment by gabbyprecious** [comment]
Hello, I would love to work on this if it has not been achieved, can I work on it?

**Comment by shinneider** [comment]
Hi @gabbyprecious 

can work on it :) 

Assign to you and create a Pull Request to `develop` branch on finish.

**Comment by gabbyprecious** [comment]
I have sent a pull request, Please review and correction will be appreciated

**Comment by shinneider** [comment]
hi @gabbyprecious 

i see the PR, and added a same comments, but i noticed that several "django tags" is reordened, not using a common django template recommendation.

however it seems to be something with its IDE (because they are lines of code that you haven't changed)

**Comment by gabbyprecious** [comment]
Hello I have sent a new pull request

**Comment by shinneider** [comment]
Hi @gabbyprecious 

I approved :)

in the next release (0.3.4) your code will be present.

as there is no loss or gain in performance or any bugs, I will not upload the version immediately
wait to another issue to create a new version :)
