### ISSUE TITLE
Django 3.0 compatibility 

### ISSUE THREAD

**Issue by cy** [shinneider/django-admin-search#25]
Hello! In Django 3.0, `{% load admin_static %}` was removed in favour of `{% load static %}` (see the second last point of https://docs.djangoproject.com/en/dev/releases/3.0/#features-removed-in-3-0)

Could this package update django_admin_search/templates/admin/custom_change_list.html and https://github.com/shinneider/django-admin-search/blob/90e382e01c95d0f79a2381b5fc580a851494f6af/django_admin_search/templates/admin/custom_search_form.html to be compatible? Thanks!

**Comment by shinneider** [comment]
Hi @cy .

It's a great improvement, and adds support to new django version. 
I add comments in your PR, because i see another fix can be done in this pr.

Many thanks. :)

**Comment by shinneider** [comment]
Hi @cy

I approved your PR, and create a new release, with your changes and anothers change that i work but not uploaded still.

Modify your `requirements.txt` to `django-admin-search>=0.3.3` to get changes.

**Comment by cy** [comment]
thanks @shinneider! 🙌
