### ISSUE TITLE
Refact advanced_search_query function

### ISSUE THREAD

**Issue by shinneider** [shinneider/django-admin-search#28]
I want to refactor `advanced_search_query ` function inside `django_admin_search/admin.py`

Because is a very large function, is hard to maintenance and developer test cases.

This function is responsible  for:
    - allow to create a custom filter for especific field (line 63 to 71)
    - get field and filter method (73 and 74)
    - apply default filter (76 to 92)

I sugeste create a specific function for all this methods.

**Comment by gabbyprecious** [comment]
Hello, I would love to work on this, can I work on it?

**Comment by shinneider** [comment]
Hi @gabbyprecious

is available to work yet :)

if you need help to understand the logic, contact me in a comment.

**Comment by gabbyprecious** [comment]
Hello, I'll need help in understanding the logic if you can break it down.

**Comment by shinneider** [comment]
Hi @gabbyprecious. 

I suggest to work in another issue, this issue is more complicated that i imagined, for this reasson i need to remove `good first issue` tag.

this changes impact a main logic of the lib.

**Comment by shinneider** [comment]
@gabbyprecious 

I suggest to work on this [issue 18](https://github.com/shinneider/django-admin-search/issues/18), it's very quick and have more bennefits

**Comment by shinneider** [comment]
refact on `0.3.6` but no has unit test yet
