### ISSUE TITLE
Create static subfolder for app

### ISSUE THREAD

**Issue by yuriescl** [shinneider/django-admin-search#33]
The `static` folder should have a subfolder named `django_admin_search` to avoid conflicting with already existing static files when running `python manage.py collectstatic`.

**Comment by shinneider** [comment]
Hi @yuriescl , sorry for long time to answer.

in this pandemic a lot has happened, international change, visa details, search for house, new job, and more, it's crazy.

But you have reasson, this is good point. 
I must go back have time in next month, and i want give attention to this lib.

but if your have time before this, open a pr and i evaluate in weekend.

**Comment by shinneider** [comment]
@Abhi904485 sorry for the long time to response, and thanks for the PR i approved today, and your change is present on the version 0.3.7
