### ISSUE TITLE
Login based search queryset to be returned.

### ISSUE THREAD

**Issue by shan3tala** [shinneider/django-admin-search#34]
1. Login based queryset object to be returned. 
Since this tool overrides the default django queryset object already, how to return the only customer domain based specific records as default , when not searched.
eg: ```
def get_queryset(self, request):
    domain_list = []
    temp = []
    qs = super(LogSearchFormAdmin, self).get_queryset(request)
    if request.user.is_superuser:
        return qs
    else:
        domain_list = Domain.objects.filter(
            customer__in=Customer.objects.filter(
                email=request.user.username)).values_list(
                    'name', flat=True)
        #print(list(domain_list))
        dom_names = list(domain_list)
        #print(dom_names)
        qs = MailLogs.objects.none()
        if dom_names:
            for d in dom_names:
                qs = MailLogs.objects.filter(
                    Q(mfrom__icontains=d)|Q(mto__icontains=d))
                
                # qs |= MailLogs.objects.filter(mfrom__icontains=d)

                # qs |=  MailLogs.objects.filter(mto__icontains=d)

                print(qs.query)
        #print(qs)
        return qs

```

**Comment by shinneider** [comment]
If you need queryset without filter you can call directly to queryset `MailLogs.objects.all()` or call to super (in this case super is my lib) if modal filter is empty all queryset is returned.

**Comment by shinneider** [comment]
@shan3tala 
If you need queryset without filter you can call directly to queryset `MailLogs.objects.all()` or call to super (in this case super is my lib) if modal filter is empty all queryset is returned.

**Comment by shinneider** [comment]
Closed because the author no submit any response.
@shan3tala
