### ISSUE TITLE
Refresh issue after returning from search form

### ISSUE THREAD

**Issue by shan3tala** [shinneider/django-admin-search#35]
Once the search is over, the page doens't refresh to return back the original set of records. Please check the url even after we remove the parameters, we don't get the original expected rows in the modeladmin view, until we make some changes in the python code and save it.

**Comment by micahaza** [comment]
I have similar problems. When I submit the form and it filters next time opening the form is empty, however the hidden search params are sent to the server so it is really confusing. 

How can I re-populate the modal form if there was a search before?

How can I reset the hidden values?

**Comment by shinneider** [comment]
Hi @micahaza @shan3tala 

Sorry for the long time to response, i was moving to another country, and i was problematic steps and I didn't have time.
but now it's all ok.

i checked and is bug, and it's solved in 0.3.6 version, please update your's libs and test and report please.

@micahaza about de empty modal, this is limitation of django-admin, i create this [PR](https://github.com/shinneider/django-admin-search/issues/15) previously, but no has solution yet.
