### ISSUE TITLE
How to use search_FieldnameHere?

### ISSUE THREAD

**Issue by shan3tala** [shinneider/django-admin-search#36]
Unable to use search_Field right now. Trying using django 3.0.5

**Comment by shinneider** [comment]
which error found? try again in version 0.3.6 please

**Comment by shinneider** [comment]
Is a error on readme, try to change received params to:

`def search_FieldNameHere(request, field, field_value, form_field, request, param_values):`
or 
`def search_FieldNameHere(request, field, field_value, **kwargs):`

on the version `0.3.X` i added new value to this, but forgot update README.

try and report result please.

**Comment by shinneider** [comment]
Closed because the author no submit any response
