### ISSUE TITLE
Version 0.3.10 stopped working after recent 'simplifcation'

### ISSUE THREAD

**Issue by Drachenfels** [shinneider/django-admin-search#44]
With this commit:

https://github.com/shinneider/django-admin-search/commit/86463f72ab835e151df1fecc7b7703cfe036c3c4#diff-87b0e17e051db518901ad65521b336894bf5652a42e5fc1f8e6ffea9896b8930

Method get_field_override was renamed into get_field_value, but there is already get_field_value on a class with a completely different signature, this makes the code explode with message: "Filter not applied, error has occurredget_field_value() missing 4 required positional arguments: 'form_field', 'field_value', 'has_field_value', and 'request'"

**Comment by shinneider** [comment]
@Drachenfels Thanks for report.
I create a version 0.3.11 with a fix.
Please test for us

but i need a maintainer, if you have time/interest please contact me.
