### ISSUE TITLE
Please release 3.12

### ISSUE THREAD

**Issue by simonwiles** [shinneider/django-admin-search#47]
The most recent release on PyPI (`3.11`, untagged here on GitHub) doesn't include the most recent commits from January which are required for compatibility with Django 4.  Please release a version `3.12` on PyPI!

(In the meantime, anyone wanting to use this with Django 4 -- or silence the deprecation warnings with Django 3 -- can use `pipenv install -e git+https://github.com/shinneider/django-admin-search@47245d8#egg=django-admin-search` or similar.)

**Comment by shinneider** [comment]
@simonwiles generated https://pypi.org/project/django-admin-search/0.3.12/
